### ISSUE TITLE
Extension seems to hit Cloudflare for every page view

### ISSUE THREAD

**Issue by Sophivorus** [harugon/mediawiki-extensions-cloudflare#6]
Hi! After a couple of weeks of using this extension, I noticed that the Cloudflare API was being hit with every page view, which effectively worsened the performance of our site. I'm not 100% sure if the Cloudflare API was being hit with literally EVERY page view (that reached the server) or only a high percentage, but in any case, as soon as I disabled this extension the problem disappeared so I'm pretty sure there's some important flaw in the logic of this extension somewhere.

Since my [previous pull request](https://github.com/harugon/mediawiki-extensions-cloudflare/pull/5) never got reviewed or merged, I decided to finish and deploy the extension I was developing rather than trying to fix this one (see https://www.mediawiki.org/wiki/Extension:CloudflarePurge). Perhaps comparing it with yours may help you identify and fix the issue. Cheers!

**Comment by harugon** [comment]
I understand the issue. This extension was rebuilt with EventRelayer, so purge requests are sent even to pages that are not cached by Cloudflare (such as user pages with settings changes, and during login).

**Comment by labster** [comment]
Is this fixed in #7 ?

**Comment by harugon** [comment]
Yes, this issue has been resolved in #7. Let me know if there’s anything else you’d like me to check!

**Comment by labster** [comment]
No, just close this issue.  Thanks!
